name: Run Tests
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: ['^16']
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn install --frozen-lockfile
    - run: yarn test
    - run: npm run package
    - name: Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ppx-debug-0.51.0.vsix
        path: ppx-debug-0.51.0.vsix
